Repository aerospaceresearch/orbitdeterminator, pull requests merged in 2020-10, with the labels that each got.

#200 Preliminary orbit determination gauss method
  orbitdeterminator/example_data/SATOBS-ML-19200716.txt
  orbitdeterminator/kep_determination/gauss_example_earth_sat.py
  orbitdeterminator/kep_determination/gauss_example_iss_jul2016.py
  orbitdeterminator/kep_determination/gauss_method.py
  orbitdeterminator/kep_determination/gibbsMethod.py
  orbitdeterminator/kep_determination/lamberts_method.py
  orbitdeterminator/kep_determination/orbital_elements.py
Labels: enhancement

#201 Preliminary orbit determination gauss method
  orbitdeterminator/kep_determination/gauss_method.py
  orbitdeterminator/kep_determination/gibbs_method.py
Labels: hacktoberfest

#203 fixed lib names
  orbitdeterminator/main.py
  orbitdeterminator/propagation/sgp4.py
Labels: bug, hacktoberfest

#204 fixed another gibbs_method link
  orbitdeterminator/main.py
Labels: bug, hacktoberfest

#205 fixed gibbs_method in test
  orbitdeterminator/tests/test_gibbsMethod.py
Labels: bug, hacktoberfest

#202 Update requirements.txt
  requirements.txt
Labels: hacktoberfest, help wanted

#206 fixed links to libs
  orbitdeterminator/tests/test_check_keplerian.py
  orbitdeterminator/tests/test_input_transf.py
  orbitdeterminator/tests/test_kalman.py
  orbitdeterminator/tests/test_lamberts_kalman.py
  orbitdeterminator/tests/test_orbit_trajectory.py
Labels: bug, hacktoberfest

#210 Final GSoC(2019) pull request replica
  orbitdeterminator/kep_determination/custom_prop.py
  orbitdeterminator/kep_determination/gauss_method.py
  orbitdeterminator/kep_determination/least_squares.py
  orbitdeterminator/util/conversion_module.py
  requirements.txt
Labels: enhancement, hacktoberfest, help wanted
