Repository aerospaceresearch/orbitdeterminator, pull requests merged in 2021-04, with the labels that each got.

#238 Preliminary orbit determination
  orbitdeterminator/doppler/requirements.txt
  orbitdeterminator/kep_determination/custom_prop.py
  orbitdeterminator/kep_determination/gauss_method.py
  orbitdeterminator/kep_determination/gibbs_method.py
  orbitdeterminator/kep_determination/lamberts_kalman.py
  orbitdeterminator/kep_determination/lamberts_method.py
  orbitdeterminator/main.py
  orbitdeterminator/propagation/sgp4.py
  orbitdeterminator/tests/test_gibbsMethod.py
  orbitdeterminator/util/__init__.pyc
  orbitdeterminator/util/conversion_module.py
  orbitdeterminator/util/read_data.pyc
  requirements.txt
Labels: duplicate, help wanted

#240 Remove pyephem dependency
  orbitdeterminator/kep_determination/gauss_method.py
  requirements.txt
Labels: enhancement, help wanted

#242 Preliminary orbit determination
  orbitdeterminator/kep_determination/gauss_method.py
  orbitdeterminator/kep_determination/orbital_elements.py
  orbitdeterminator/main.py
Labels: bug, enhancement

#244 Input format detection
  orbitdeterminator/kep_determination/custom_prop.py
  orbitdeterminator/kep_determination/gauss_method.py
  orbitdeterminator/kep_determination/least_squares.py
  orbitdeterminator/kep_determination/positional_observation_reporting.py
  orbitdeterminator/main.py
  orbitdeterminator/propagation/dgsn_simulator.py
  orbitdeterminator/propagation/sgp4.py
  orbitdeterminator/propagation/sgp4_prop.py
  orbitdeterminator/propagation/simulator.py
  orbitdeterminator/util/read_data.py
Labels: enhancement
